import type { TranslationIndex } from "./index.js";

export function generateTypeDeclaration(index: TranslationIndex): string {
  const keys = Object.keys(index).sort();

  if (keys.length === 0) {
    return buildDeclaration("string");
  }

  const union = keys.map((k) => `    | "${k}"`).join("\n");
  return buildDeclaration(union);
}

function buildDeclaration(keyType: string): string {
  const typeValue = keyType === "string" ? "string" : `\n${keyType}`;

  return `// Auto-generated by laravel-vite-translations
// Do not edit manually

declare module "laravel-vite-translations/runtime" {
  export type TranslationKey = ${typeValue};

  export interface I18nOptions {
    locale?: string;
    fallbackLocale?: string;
    cdnUrl?: string | null;
  }

  export interface I18nInstance {
    t: (key: TranslationKey, params?: Record<string, string | number>) => string;
    setLocale: (locale: string) => Promise<void>;
    getLocale: () => string;
    preload: (key: TranslationKey) => Promise<void>;
    onLocaleChange: (cb: (locale: string) => void) => () => void;
  }

  export function createI18n(options?: I18nOptions): I18nInstance;
}
`;
}
