// Auto-generated by laravel-vite-translations
// Do not edit manually

declare module "laravel-vite-translations/runtime" {
  export type TranslationKey = 
    | "dashboard.stats.active"
    | "dashboard.stats.revenue"
    | "dashboard.stats.total"
    | "dashboard.title"
    | "dashboard.welcome";

  export interface I18nOptions {
    locale?: string;
    fallbackLocale?: string;
    cdnUrl?: string | null;
  }

  export interface I18nInstance {
    t: (key: TranslationKey, params?: Record<string, string | number>) => string;
    setLocale: (locale: string) => Promise<void>;
    getLocale: () => string;
    preload: (key: TranslationKey) => Promise<void>;
    onLocaleChange: (cb: (locale: string) => void) => () => void;
  }

  export function createI18n(options?: I18nOptions): I18nInstance;
}
